[package]
name = "untitled"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
android_logger = "0.11.0"
android-activity = { version = "0.5.2", features = ["native-activity"] }
ndk-sys = "0.5.0"
ndk = "0.8.0"

[lib]
#name="na_mainloop"
crate_type=["cdylib"]